name: "Parky's News"
favicon: null
layout_spectrum: 0.49629
typography_spectrum: 0.75866
title: Ian Parkinson - The News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#556282'
    - '#0f131c'
    - '#fffff2'
    - '#fdde9b'
    - '#99a4b6'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
