name: "Parky's News"
favicon: null
layout_spectrum: 0.49629
typography_spectrum: 0.75866
title: Ian Parkinson - The News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfe2f3'
    - '#0d0f0e'
    - '#696969'
    - '#adc0e0'
    - '#8a8c89'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
