name: "Parky's News"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50866
title: Ian Parkinson - The News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d8ac1'
    - '#91b0dc'
    - '#d4dee9'
    - '#333552'
    - '#070318'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
