title: Ian Parkinson - The News
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3007519
  brandStrength: 0.8966165
  lightness: 0.8339599
  brandColors:
    - '#4360B0'
    - '#11141B'
    - '#FFFEFF'
    - '#83899F'
    - '#ABBBCA'
  rhythmicContrast: 0.7838346
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Parky's News"
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9154136
layout_spectrum: 0.7324561
