name: "Parky's News"
favicon: null
layout_spectrum: 0.3760456561576575
typography_spectrum: 0.19546724390238523
title: Ian Parkinson - The News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffd9a'
    - '#829d00'
    - '#2b2f00'
    - '#bab5b4'
    - '#df434c'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
