typography_spectrum: 0.4066416
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.7882205
title: Ian Parkinson - The News
purpose: []
color:
  saturation: 0.75
  brandStrength: 0.8966165
  rhythmicContrast: 0.75
  brandColors:
    - '#171716'
    - '#808680'
    - '#98ACCF'
    - '#FFFFFF'
    - '#FF2F3B'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Parky's News"
