title: Ian Parkinson - The News
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5269424
  brandStrength: 0.8966165
  lightness: 0.6328321
  brandColors:
    - '#FFFFFF'
    - '#AAD1EE'
    - '#676358'
    - '#0A0806'
    - '#9D998C'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Parky's News"
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9154136
layout_spectrum: 0.7882205
