name: "Parky's News"
favicon: null
layout_spectrum: 0.3760456561576575
typography_spectrum: 0.19546724390238523
title: Ian Parkinson - The News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e1716'
    - '#b1d7ca'
    - '#feffff'
    - '#82aaa2'
    - '#3e5250'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.7350830077193677
purpose: []
